/*
 * @Author (Derek Shaheen)
 * @since 3/20/18
 */
package higherlower;

import java.awt.Color;

public class HigherLowerController extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public HigherLowerController() {
        initComponents(); 
        this.setLocationRelativeTo(null);
        theModel = new HigherLowerModel();
        textNumber.setText(theModel.getString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textScore = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        buttonHigher = new javax.swing.JButton();
        buttonLower = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelResult = new javax.swing.JLabel();
        labelRoundNum = new javax.swing.JLabel();
        labelRange = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Higher / Lower");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textNumber.setEditable(false);
        textNumber.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        textNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textNumber.setText("0");
        getContentPane().add(textNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 74, 99, 62));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel1.setText("Current Score");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 18, -1, -1));

        textScore.setEditable(false);
        textScore.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        textScore.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textScore.setText("0");
        getContentPane().add(textScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 74, 99, 62));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel2.setText("Current Number");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 18, -1, -1));

        buttonHigher.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        buttonHigher.setText("Higher");
        buttonHigher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHigherActionPerformed(evt);
            }
        });
        getContentPane().add(buttonHigher, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 154, 161, 46));

        buttonLower.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        buttonLower.setText("Lower");
        buttonLower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLowerActionPerformed(evt);
            }
        });
        getContentPane().add(buttonLower, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 210, 161, 46));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Round #");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 269, -1, -1));

        labelResult.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        getContentPane().add(labelResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 72, -1, -1));

        labelRoundNum.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        labelRoundNum.setText("1");
        labelRoundNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRoundNumMouseClicked(evt);
            }
        });
        getContentPane().add(labelRoundNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 90, 20));

        labelRange.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        labelRange.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRange.setText("(0-99)");
        labelRange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelRangeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelRangeMouseExited(evt);
            }
        });
        getContentPane().add(labelRange, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 100, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setText("Derek Shaheen 03/2018");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHigherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHigherActionPerformed
        theModel.gen();
        choiceResult = theModel.checkChoice(1); //higher
        setTextBoxes();
    }//GEN-LAST:event_buttonHigherActionPerformed

    private void buttonLowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLowerActionPerformed
        theModel.gen();
        choiceResult = theModel.checkChoice(0); //lower
        setTextBoxes();
    }//GEN-LAST:event_buttonLowerActionPerformed

    private void labelRoundNumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRoundNumMouseClicked
        roundNum = 1; // game is reset by clicking the round counter
        theModel.reset();
        theModel.gen();
        setTextBoxes();
        labelResult.setText(""); 
        textScore.setForeground(Color.black);
    }//GEN-LAST:event_labelRoundNumMouseClicked

    private void labelRangeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRangeMouseEntered
        labelRange.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        labelRange.setText("( 0 - 99 )");
    }//GEN-LAST:event_labelRangeMouseEntered

    private void labelRangeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRangeMouseExited
        labelRange.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        labelRange.setText("(0-99)");
    }//GEN-LAST:event_labelRangeMouseExited

    /**
     *  method setTextBoxes() : set all of the set boxes when called
     */
    public void setTextBoxes() {
        if(choiceResult > 0) { 
            labelResult.setText("Correct"); 
            textScore.setForeground(Color.green);
        }
        else { 
            labelResult.setText("Incorrect");
            textScore.setForeground(Color.red);
        }
        textScore.setText(theModel.getScore());
        textNumber.setText(theModel.getString());
        labelRoundNum.setText(Integer.toString(roundNum++));
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HigherLowerController().setVisible(true);
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHigher;
    private javax.swing.JButton buttonLower;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelRange;
    private javax.swing.JLabel labelResult;
    private javax.swing.JLabel labelRoundNum;
    private javax.swing.JTextField textNumber;
    private javax.swing.JTextField textScore;
    // End of variables declaration//GEN-END:variables
    private final HigherLowerModel theModel;
    public int roundNum = 2;
    public int choiceResult;
}

